name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: podman run --rm -it fedora "echo hi"
      - name: Check out repository code
        uses: actions/checkout@v2
