name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: podman run --rm -it fedora /bin/bash -c "echo hi"
      - name: Check out repository code
        uses: actions/checkout@v2
